export enum Tag {
    a = 'A',
    del = 'DEL',
    hr = 'HR',
    h1 = 'H1',
    h2 = 'H2',
    h3 = 'H3',
    h4 = 'H4',
    h5 = 'H5',
    h6 = 'H6',
    meter = 'METER',
    progress = 'PROGRESS',
    s = 'S',
    u = 'U',
}
